package system

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

// TestReadResolvConfNameservers exercises the second-tier DNS fallback —
// every realistic shape /etc/resolv.conf can take needs to round-trip
// through this parser, since on hosts without systemd-resolved this is
// the ONLY way the migration recovers DNS. Regression test for the
// production failure on 192.168.2.216 in v6.5.6 (resolvectl missing →
// migration silently dropped the user's DNS servers).
func TestReadResolvConfNameservers(t *testing.T) {
	cases := []struct {
		name string
		body string
		want []string
	}{
		{
			name: "two nameservers no comments",
			body: "nameserver 192.168.2.4\nnameserver 192.168.2.33\n",
			want: []string{"192.168.2.4", "192.168.2.33"},
		},
		{
			name: "with header and search line",
			body: "# Generated by NetworkManager\nsearch chezmoi.ca\nnameserver 1.1.1.1\nnameserver 8.8.8.8\n",
			want: []string{"1.1.1.1", "8.8.8.8"},
		},
		{
			name: "duplicates collapsed",
			body: "nameserver 9.9.9.9\nnameserver 9.9.9.9\nnameserver 1.0.0.1\n",
			want: []string{"9.9.9.9", "1.0.0.1"},
		},
		{
			name: "mixed comments and blanks",
			body: "\n# one\n;two\nnameserver 192.0.2.1   # quad-9 comment\n\nnameserver 192.0.2.2\n",
			want: []string{"192.0.2.1", "192.0.2.2"},
		},
		{
			name: "no nameserver entries",
			body: "search example.com\noptions edns0\n",
			want: nil,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "resolv.conf")
			if err := os.WriteFile(path, []byte(tc.body), 0o644); err != nil {
				t.Fatal(err)
			}
			got := readResolvConfNameservers(path)
			if !reflect.DeepEqual(got, tc.want) {
				t.Errorf("readResolvConfNameservers(%q) = %v, want %v", tc.name, got, tc.want)
			}
		})
	}
}

// TestReadResolvConfNameserversMissing — the migration must tolerate the
// file simply not existing (the systemd-resolved-stub-symlink form on a
// host where resolved is also down).
func TestReadResolvConfNameserversMissing(t *testing.T) {
	got := readResolvConfNameservers(filepath.Join(t.TempDir(), "does-not-exist"))
	if got != nil {
		t.Errorf("expected nil for missing file, got %v", got)
	}
}

// TestParseNetplanNameservers covers the third-tier fallback. Both inline
// list and block-list shapes are accepted. The parser shares its
// indent-aware section detector with scanNetplanYAMLs, so a regression
// in either is caught here.
func TestParseNetplanNameservers(t *testing.T) {
	yaml := `network:
  version: 2
  renderer: networkd
  ethernets:
    enp5s0:
      addresses: [192.168.2.216/24]
      gateway4: 192.168.2.1
      nameservers:
        addresses: [192.168.2.4, 192.168.2.33]
        search: [chezmoi.ca]
    eno2:
      dhcp4: true
      nameservers:
        addresses:
          - 1.1.1.1
          - 1.0.0.1
`
	got := map[string][]string{}
	parseNetplanNameserversInto(yaml, got)
	want := map[string][]string{
		"enp5s0": {"192.168.2.4", "192.168.2.33"},
		"eno2":   {"1.1.1.1", "1.0.0.1"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("parseNetplanNameserversInto =\n  got  %v\n  want %v", got, want)
	}
}

// TestParseNetplanNameserversNoEthernets — bonds/bridges/etc. shouldn't
// contribute DNS. This guards against accidental scope creep that would
// pull DNS from an unsupported section into the migration.
func TestParseNetplanNameserversNoEthernets(t *testing.T) {
	yaml := `network:
  version: 2
  bridges:
    br0:
      nameservers:
        addresses: [10.0.0.1]
`
	got := map[string][]string{}
	parseNetplanNameserversInto(yaml, got)
	if len(got) != 0 {
		t.Errorf("non-ethernet sections leaked DNS into result: %v", got)
	}
}
